"""empty message

Revision ID: 122264c1c66b
Revises: 3c29246f8e4f
Create Date: 2023-12-05 16:39:26.558502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122264c1c66b'
down_revision = '3c29246f8e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###
