"""empty message

Revision ID: 3c11e1f6f7b6
Revises: 
Create Date: 2023-12-15 20:31:26.823009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c11e1f6f7b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=2500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=2500),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###
